# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build and deploy

on:
  push:
    tags:
      - "*"

env:
  APP_NAME: shiftlee-image-optimizer
  RESOURCE_GROUP: shiftlee

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build & publish
        run: |
          dotnet publish -c Release -o ./.publish/web
          cd ./.publish/web && zip -r ../web.zip .

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure deploy
        run: az webapp deployment source config-zip -g $RESOURCE_GROUP -n $APP_NAME --src ./.publish/web.zip

      - name: Azure logout
        run: az logout
